const jokes = ["What did the horse say after it tripped?\nHelp! I’ve fallen and I can’t giddy-up!" ,
    "Why can't you hear a pterodactyl going to the bathroom?\nBecause the “P” is silent.",
  "What do you call a well-balanced horse?\nStable.",
  "What do you call an angry carrot?\nA steamed veggie.",
  "Where do polar bears keep their money?\nIn a snowbank.",
  "How do you make an egg roll?\nYou push it!",
  "What would bears be without bees?\nEars.",
  "What do you call a pile of cats?\nA meow-ntain.",
  "Why do cows wear bells?\nBecause their horns don’t work.",
  "Why did the bicycle fall over?\nBecause it was two tired.",
  "What did the triangle say to the circle?\nYou’re pointless.",
  "RIP, boiling water.\nYou will be mist.",
  "Time flies like an arrow.\nFruit flies like a banana.",
  "I ordered a chicken and an egg online.\nI’ll let you know what comes first.",
  "Why was Cinderella so bad at soccer?\nShe kept running away from the ball!",
  "What do lawyers wear to court?\nLawsuits.",
  "What do elves learn in school?\nThe elf-abet.",
  "Where was King David’s temple located?\nBeside his ear.",
  "What did one toilet say to another?\nYou look flushed.",
  "What lights up a soccer stadium?\nA soccer match.",
  "What does corn say when it gets a compliment?\nAw, shucks!",
  "What’s the difference between a poorly dressed man on a tricycle and a well-dressed man on a bicycle?\nAttire.",
  "What’s red and bad for your teeth?\nA brick.",
  "What do sprinters eat before they race?\nNothing. They fast.",
  "What has more lives than a cat?\nA frog, because it croaks every day.",
  "A bossy man walked into a bar…\nAnd ordered everyone a round.",
  "What’s Forrest Gump’s password?\n1forrest1.",
  "What do you call a fish without an eye?\nFsh.",
  "What do you call a pig that practices karate?\nA pork chop.",
  "Do you know what they say about a clean desk?\nIt's a sure sign of a cluttered desk drawer.",
  "How did the barber win the race?\nHe knew a short cut.",
  "I told my friend 10 jokes to make him laugh.\nSadly, no pun in ten did." ,
  "Two fish are in a tank.\nOne turns to the other and says, “Any idea how to drive this thing?”",
  "What did the tomato say to the other tomato during a race?\nKetchup.",
  "Why shouldn’t you write with a broken pen?\nBecause it’s pointless.",
  "Why can't you trust the king of the jungle?\nBecause he's always lion.",
  "What did one wall say to the other?\n\"I'll meet you at the corner.\"",
  "What do sea monsters eat?\nFish and ships.",
  "What do you call a sad strawberry?\nA blueberry!",
  "Why are pirates called pirates?\nThey just ARRRR!",
  "How do you organize a space party?\nYou planet.",
  "Why do seagulls fly over the sea?\nIf they flew over the bay, they would be bagels.",
  "What do cows read the most?\nCattle-logs.",
  "I lost an electron.\nYou really have to keep an ion them!",
  "What do clouds wear under their shorts?\nThunder pants!",
  "How many tickles does it take to make an octopus laugh?\nTen-tickles.",
  "What did 0 say to 8?\n\"Nice belt.\"",
  "How did the hipster burn his tongue?\nHe drank his coffee before it was cool.",
  "What did the drummer name her twin daughters?\nAnna 1, Anna 2.",
  "What did the lettuce say to the celery?\nQuit stalking me!",
  "What’s small and red and has a rough voice?\nA hoarse raddish!",
  "Why do mushrooms get invited to all the parties?\nBecause they are such fungis.",
  "Why shouldn’t you tell secrets in a cornfield?\nToo many ears.",
  "Why couldn’t the bad sailor learn the alphabet?\nBecause he always got lost at “C.”",
  "How bad were the fish’s grades?\nThey were below sea level.",
  "What do you call a shoe made out of a banana?\nA slipper.",
  "How many computer programmers does it take to change a light bulb?\nNone, that's a hardware problem!",
  "I’m reading a book about anti-gravity.\nI can’t put it down.",
  "What kind of cheese isn’t yours?\nNacho cheese.",
  "What does a spy do when he is cold?\nHe goes undercover.",
  "How does the moon cut his hair?\nEclipse it.",
  "When do computers overheat?\nWhen they need to vent.",
  "Why did the scarecrow win an award?\nBecause he was outstanding in his field.",
  "If athletes get athlete’s foot, what do elves get?\nMistle-toes.",
  "What’s brown and sticky?\nA stick.",
  "What do you call a sad cup of coffee?\nDepresso.",
  "How did the telephone propose to his girlfriend?\nHe gave her a ring.",
  "What did the cucumber say to the pickle?\nYou mean a great dill to me.",
  "Where did the lettuce go for a drink?\nThe salad bar.",
  "Did you hear the rumor about butter?\nWell, I'm not going to go spreading it!",
  "What happens when a snowman throws a tantrum?\nHe has a meltdown.",
  "What goes up and down but doesn’t move?\nStairs.",
  "Why did the cookie go to the hospital?\nBecause he felt crumby.",
  "What did the janitor say when he jumped out of the closet?\nSupplies!",
  "What do you get when you cross a fish and an elephant?\nSwimming trunks.",
  "What did the worker at the rubber band factory say when he was fired?\nOh, snap.",
  "Why can’t a nose be 12 inches long?\nBecause then it would be a foot.",
  "Why did the belt go to jail?\nBecause it held up a pair of pants.",
  "Where does the general put his armies?\nIn his sleevies.",
  "What do you call a magician that loses his magic?\nIan.",
  "Why did the golfer bring two pairs of pants?\nIn case he got a hole-in-one.",
  "What did the yoga instructor say when her landlord tried to evict her?\nNamaste.",
  "How do rabbits travel?\nBy hareplanes.",
  "What do you call a sleeping dinosaur?\nA dino-snore.",
  "Why did the kid stock up on yeast?\nHe wanted to make some dough.",
  "What did the football coach say to the broken vending machine?\nGive me my quarterback.",
  "Why are elephants wrinkly?\nBecause you can’t iron them.",
  "What did the cake say to the fork?\nYou want a piece of me?",
  "How did the two cats end their fight?\nThey hissed and made up.",
  "Why did the strawberry cry?\nHe found himself in a jam.",
  "What’s black and white and read all over?\nA newspaper!",
  "What do you say to a cow that gets in your way?\n“Moooo-ve!”",
  "What did 50 Cent do when he was hungry?\n58!",
  "What did the nut say to the other nut in a game of tag?\nImma cashew!",
  "Why did an old man fall in a well?\nBecause he couldn’t see that well!",
  "Why is Peter Pan always flying?\nBecause he Neverlands.",
  "Why don’t astronomers like Orion’s Belt?\nIt’s a big waist of space.",
  "What do you call a hippie’s wife?\nMississippi.",
  "Why are peppers the best at archery?\nBecause they habanero!",
  "How do you tell the difference between a bull and a cow?\nIt is either one or the udder!"
]
function generator(){
    let value = Math.floor(Math.random()*jokes.length);
    console.log(value)
    let joke = jokes[value];
    document.getElementById('joke').innerText = joke;
}